name: Bug Report
description: Report a bug that needs to be fixed
title: "[BUG]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide all the required information to help us understand and process your issue efficiently.

  - type: textarea
    id: users_impact
    attributes:
      label: User's Impact
      description: Describe how this issue impacts users
      placeholder: "Example: Users cannot access their data when..."
    validations:
      required: true

  - type: textarea
    id: url
    attributes:
      label: Document URL
      description: Please provide a URL to affected document
      placeholder: "https://..."
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide detailed information about the bug
      placeholder: "Bug detail description
                    Describe the bug in detail.
                    
                    Preconditions
                    Specific configuration or resource setup needed to reproduce
                    
                    How to reproduce
                    Describe the simplest way to reproduce the scenario.
                    
                    IDs of used resources
                    Describe all relevant and impacted resources from the bug. The affected tenant and project IDs should be described.
                    
                    Result of the issue
                    Describe the issue results.
                    
                    Expected result
                    Documentation (optional)
                    To add additional documentation is use case depended. It should help to understand the bug faster from R&D.
                    
                    Workaround (optional)
                    Described the workaround when exists. This information is important for the service approval KPIs."
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (logs, screenshots, etc.)
      placeholder: "Logs, error messages, screenshots, environment details..."
    validations:
      required: false
